
import { Project, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Ali Ahmed",
    email: "ali.ahmed@example.com",
    userType: "farmer",
    avatar: "/placeholder.svg",
    verified: true,
  },
  {
    id: "u2",
    name: "Fatima Khan",
    email: "fatima.khan@example.com",
    userType: "investor",
    avatar: "/placeholder.svg",
    verified: true,
  },
  {
    id: "u3",
    name: "Muhammad Hassan",
    email: "m.hassan@example.com",
    userType: "farmer",
    avatar: "/placeholder.svg",
    verified: true,
  },
  {
    id: "u4",
    name: "Ayesha Malik",
    email: "ayesha.malik@example.com",
    userType: "investor",
    avatar: "/placeholder.svg",
    verified: true,
  },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    title: "Organic Rice Farm in Sindh",
    description: "A 5-acre organic rice farm using sustainable farming practices. This project aims to produce premium basmati rice for both local consumption and export markets. Investment will go toward irrigation improvements, organic fertilizers, and harvesting equipment.",
    farmerId: "u1",
    farmerName: "Ali Ahmed",
    location: "Larkana, Sindh",
    cropType: "Rice",
    fundingGoal: 500000,
    fundingRaised: 325000,
    duration: 6,
    expectedROI: 18,
    status: "active",
    images: ["/placeholder.svg"],
    createdAt: new Date("2023-11-10"),
    startDate: new Date("2023-12-01"),
    endDate: new Date("2024-06-01"),
  },
  {
    id: "p2",
    title: "Wheat Cultivation in Punjab",
    description: "A 10-acre wheat farm in fertile Punjab region. We are implementing modern techniques to increase yield and quality. Funding will support seed purchase, machinery rental, and labor costs for the entire growing cycle.",
    farmerId: "u3",
    farmerName: "Muhammad Hassan",
    location: "Multan, Punjab",
    cropType: "Wheat",
    fundingGoal: 750000,
    fundingRaised: 220000,
    duration: 4,
    expectedROI: 15,
    status: "active",
    images: ["/placeholder.svg"],
    createdAt: new Date("2023-12-05"),
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-05-15"),
  },
  {
    id: "p3",
    title: "Mango Orchard Expansion",
    description: "Expansion of an existing mango orchard to include premium varieties for export markets. This project will add 3 acres of new mango trees and implement drip irrigation systems to optimize water usage.",
    farmerId: "u1",
    farmerName: "Ali Ahmed",
    location: "Mirpur Khas, Sindh",
    cropType: "Mango",
    fundingGoal: 1200000,
    fundingRaised: 600000,
    duration: 12,
    expectedROI: 25,
    status: "pending",
    images: ["/placeholder.svg"],
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "p4",
    title: "Cotton Farming Modernization",
    description: "Modernizing a 7-acre cotton farm with better seeds, pest management, and harvesting techniques. This project aims to increase yield by 30% while reducing water usage through better irrigation methods.",
    farmerId: "u3",
    farmerName: "Muhammad Hassan",
    location: "Bahawalpur, Punjab",
    cropType: "Cotton",
    fundingGoal: 850000,
    fundingRaised: 850000,
    duration: 5,
    expectedROI: 16,
    status: "funded",
    images: ["/placeholder.svg"],
    createdAt: new Date("2024-02-10"),
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-08-01"),
  },
  {
    id: "p5",
    title: "Vegetable Greenhouse Project",
    description: "Construction of two modern greenhouses for year-round vegetable production including tomatoes, cucumbers, and bell peppers. This controlled environment will maximize yield while minimizing pest issues and water usage.",
    farmerId: "u1",
    farmerName: "Ali Ahmed",
    location: "Swat, KPK",
    cropType: "Vegetables",
    fundingGoal: 1500000,
    fundingRaised: 750000,
    duration: 8,
    expectedROI: 22,
    status: "active",
    images: ["/placeholder.svg"],
    createdAt: new Date("2023-10-15"),
    startDate: new Date("2023-11-01"),
    endDate: new Date("2024-07-01"),
  },
  {
    id: "p6",
    title: "Dairy Farm Enhancement",
    description: "Expansion of an existing dairy farm to add 10 high-yielding cattle and improve feed production on adjacent farmland. The project includes building modern housing facilities and implementing improved feeding practices.",
    farmerId: "u3",
    farmerName: "Muhammad Hassan",
    location: "Sahiwal, Punjab",
    cropType: "Livestock",
    fundingGoal: 2000000,
    fundingRaised: 1250000,
    duration: 10,
    expectedROI: 20,
    status: "active",
    images: ["/placeholder.svg"],
    createdAt: new Date("2023-11-01"),
    startDate: new Date("2023-12-15"),
    endDate: new Date("2024-10-15"),
  },
];

export const cropTypes = [
  "Rice",
  "Wheat",
  "Cotton",
  "Sugarcane",
  "Maize",
  "Vegetables",
  "Fruits",
  "Mango",
  "Livestock",
  "Other",
];

export const pakistanLocations = [
  "Karachi, Sindh",
  "Lahore, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Multan, Punjab",
  "Hyderabad, Sindh",
  "Peshawar, KPK",
  "Quetta, Balochistan",
  "Islamabad, Federal",
  "Sialkot, Punjab",
  "Bahawalpur, Punjab",
  "Larkana, Sindh",
  "Mirpur Khas, Sindh",
  "Swat, KPK",
  "Sahiwal, Punjab",
];
